import * as fs from 'node:fs';
import * as path from 'node:path';
import { getRuntimePlatformCapabilities } from '../runtime-platform.js';
import type {
  SkillGovernanceAction,
  SkillGovernanceDetection,
  SkillGovernanceReportItem,
  SkillGovernanceVerdict,
  WorkspaceSkillGovernanceReport,
} from '../types.js';
import {
  extractChecklistItems,
  extractCommandCandidates,
  normalizeWorkflowText,
} from '../utils/workflow-signal.js';
import type { SkillWriteRecord } from './SkillWriteStore.js';
import { SkillWriteStore } from './SkillWriteStore.js';
import { parseSkillMarkdown, readSkillVersion, upsertSkillMetadata } from './skill-markdown.js';
import type {
  AutoGeneratedSkillGovernanceServiceDeps,
  DetectionContext,
  GovernanceSkillRecord,
  LlmReviewItem,
} from './auto-generated-skill-governance-contracts.js';
import {
  extractJsonObject,
  normalizePlatformMetadata,
  nowIso,
  similarityScore,
  sortWriteRecordsByRecency,
} from './auto-generated-skill-governance-utils.js';

export type { AutoGeneratedSkillGovernanceServiceDeps } from './auto-generated-skill-governance-contracts.js';

export class AutoGeneratedSkillGovernanceService {
  private readonly skillWriteStore: SkillWriteStore;
  private readonly getWorkspaceToolsetName: AutoGeneratedSkillGovernanceServiceDeps['getWorkspaceToolsetName'];
  private readonly getLlmClient: AutoGeneratedSkillGovernanceServiceDeps['getLlmClient'];
  private readonly reloadSkills: AutoGeneratedSkillGovernanceServiceDeps['reloadSkills'];
  private readonly publishWorkspaceGeneratedPack: AutoGeneratedSkillGovernanceServiceDeps['publishWorkspaceGeneratedPack'];
  private readonly activeWorkspaceRuns = new Set<string>();

  constructor(deps: AutoGeneratedSkillGovernanceServiceDeps) {
    this.skillWriteStore = deps.skillWriteStore;
    this.getWorkspaceToolsetName = deps.getWorkspaceToolsetName;
    this.getLlmClient = deps.getLlmClient;
    this.reloadSkills = deps.reloadSkills;
    this.publishWorkspaceGeneratedPack = deps.publishWorkspaceGeneratedPack;
  }

  async run(input: {
    workspaceDir: string;
    runId?: string;
  }): Promise<WorkspaceSkillGovernanceReport> {
    const workspaceDir = path.resolve(input.workspaceDir);
    const runId = input.runId?.trim() || `workspace-skill-governance-${Date.now()}`;
    if (this.activeWorkspaceRuns.has(workspaceDir)) {
      throw new Error(`workspace skill governance already running: ${workspaceDir}`);
    }
    this.activeWorkspaceRuns.add(workspaceDir);
    try {
      return await this.runUnlocked({ workspaceDir, runId });
    } finally {
      this.activeWorkspaceRuns.delete(workspaceDir);
    }
  }

  private async runUnlocked(input: {
    workspaceDir: string;
    runId: string;
  }): Promise<WorkspaceSkillGovernanceReport> {
    const backfill = this.backfillMetadata(input.workspaceDir);
    const inventory = this.scanAutoGeneratedSkills(input.workspaceDir);
    if (inventory.length === 0) {
      return this.buildReport({
        workspaceDir: input.workspaceDir,
        runId: input.runId,
        fallback: false,
        scannedSkills: 0,
        exactDuplicates: 0,
        candidateDuplicates: 0,
        autoArchived: 0,
        reportOnly: 0,
        boundaryFixed: backfill.boundaryFixedCount,
        conflicts: 0,
        items: [],
      });
    }

    const detection = this.detectCandidates(inventory);
    const review = await this.reviewInventory(inventory, detection);
    const items = this.buildReportItems(inventory, detection, review.items);
    let autoArchived = 0;
    let touchedWorkspace = false;

    if (!review.fallback) {
      for (const item of items) {
        if (item.action !== 'soft_archive' || !item.canonicalTargetPath) {
          continue;
        }
        const skill = inventory.find((entry) => entry.id === item.id);
        if (!skill) {
          continue;
        }
        if (this.softArchiveSkill(skill, item.canonicalTargetPath, input.runId)) {
          autoArchived += 1;
          touchedWorkspace = true;
        }
      }
    }

    if (autoArchived > 0 || backfill.provenanceBackfillCount > 0) {
      this.reloadSkills();
    }
    if (touchedWorkspace) {
      this.publishWorkspaceGeneratedPack(input.workspaceDir);
    }

    return this.buildReport({
      workspaceDir: input.workspaceDir,
      runId: input.runId,
      fallback: review.fallback,
      fallbackReason: review.fallbackReason,
      scannedSkills: inventory.length,
      exactDuplicates: detection.exactDuplicateIds.size,
      candidateDuplicates: detection.candidateDuplicateIds.size,
      autoArchived,
      reportOnly: items.filter((item) => item.action === 'none' && item.verdict !== 'keep').length,
      boundaryFixed: backfill.boundaryFixedCount,
      conflicts: items.filter(
        (item) =>
          item.verdict === 'keep_separate_conflict' ||
          item.verdict === 'needs_manual_review' ||
          item.detection === 'name_conflict'
      ).length,
      items,
    });
  }

  private backfillMetadata(seedWorkspaceDir: string): {
    boundaryFixedCount: number;
    provenanceBackfillCount: number;
  } {
    const workspaceDir = path.resolve(seedWorkspaceDir);
    const workspaceSkillsDir = path.join(workspaceDir, 'skills');
    const records = sortWriteRecordsByRecency(
      this.skillWriteStore.listWriteRecords({
        status: 'applied',
        workspaceDir,
        reason: 'repeated_success_pattern',
      })
    );
    const latestByPath = new Map<string, SkillWriteRecord>();
    for (const record of records) {
      const key = path.resolve(record.targetPath);
      const relative = path.relative(workspaceSkillsDir, key);
      if (relative.startsWith('..') || path.isAbsolute(relative)) {
        continue;
      }
      if (!latestByPath.has(key)) {
        latestByPath.set(key, record);
      }
    }

    let boundaryFixedCount = 0;
    let provenanceBackfillCount = 0;
    for (const record of latestByPath.values()) {
      if (!fs.existsSync(record.targetPath)) {
        continue;
      }
      const currentContent = fs.readFileSync(record.targetPath, 'utf-8');
      const parsed = parseSkillMarkdown(currentContent);
      const patch: Record<string, unknown> = {};
      let changed = false;
      let boundaryChanged = false;
      if (String(parsed.metadata.generatedBy ?? '').trim() !== 'auto-observe-turn') {
        patch.generatedBy = 'auto-observe-turn';
        changed = true;
        provenanceBackfillCount += 1;
      }
      if (String(parsed.metadata.generationReason ?? '').trim() !== 'repeated_success_pattern') {
        patch.generationReason = 'repeated_success_pattern';
        changed = true;
      }
      if (!String(parsed.metadata.sourceFingerprint ?? '').trim() && record.sourceFingerprint) {
        patch.sourceFingerprint = record.sourceFingerprint;
        changed = true;
      }
      if (!String(parsed.metadata.sourceSessionId ?? '').trim() && record.sourceSessionId) {
        patch.sourceSessionId = record.sourceSessionId;
        changed = true;
      }
      if (!String(parsed.metadata.originToolset ?? '').trim() && record.originToolset) {
        patch.originToolset = record.originToolset;
        changed = true;
      }
      if (!String(parsed.metadata.originPlatform ?? '').trim() && record.originPlatform) {
        patch.originPlatform = record.originPlatform;
        changed = true;
      }
      if (!String(parsed.metadata.generatedAt ?? '').trim()) {
        patch.generatedAt = record.generatedAt ?? record.appliedAt ?? record.updatedAt ?? record.createdAt;
        changed = true;
      }

      const existingToolsets = Array.isArray(parsed.metadata.toolsets)
        ? (parsed.metadata.toolsets as unknown[]).map((item) => String(item ?? '').trim()).filter(Boolean)
        : [];
      if (existingToolsets.length === 0) {
        const fallbackToolset =
          record.originToolset ||
          this.getWorkspaceToolsetName(record.workspaceDir || seedWorkspaceDir) ||
          'full-access';
        patch.toolsets = [fallbackToolset];
        changed = true;
        boundaryChanged = true;
      }
      const existingPlatforms = Array.isArray(parsed.metadata.platforms)
        ? (parsed.metadata.platforms as unknown[]).map((item) => String(item ?? '').trim()).filter(Boolean)
        : [];
      if (existingPlatforms.length === 0) {
        const fallbackPlatformsFromRecord = normalizePlatformMetadata(record.originPlatform);
        const fallbackPlatforms =
          fallbackPlatformsFromRecord.length > 0
            ? fallbackPlatformsFromRecord
            : normalizePlatformMetadata(getRuntimePlatformCapabilities().platform);
        patch.platforms = fallbackPlatforms.length > 0 ? fallbackPlatforms : ['windows'];
        changed = true;
        boundaryChanged = true;
      }

      if (!changed) {
        continue;
      }
      fs.writeFileSync(record.targetPath, upsertSkillMetadata(currentContent, patch), 'utf-8');
      if (boundaryChanged) {
        boundaryFixedCount += 1;
      }
    }

    return {
      boundaryFixedCount,
      provenanceBackfillCount,
    };
  }

  private scanAutoGeneratedSkills(seedWorkspaceDir: string): GovernanceSkillRecord[] {
    const workspaceDir = path.resolve(seedWorkspaceDir);
    const rootDir = path.join(workspaceDir, 'skills');
    const items = new Map<string, GovernanceSkillRecord>();
    if (!fs.existsSync(rootDir)) {
      return [];
    }
    const stack = [rootDir];
    while (stack.length > 0) {
      const current = stack.pop();
      if (!current || !fs.existsSync(current)) {
        continue;
      }
      const entries = fs.readdirSync(current, { withFileTypes: true });
      const skillFile = entries.find((entry) => entry.isFile() && entry.name.toLowerCase() === 'skill.md');
      if (skillFile) {
        const targetPath = path.join(current, skillFile.name);
        const raw = fs.readFileSync(targetPath, 'utf-8');
        const parsed = parseSkillMarkdown(raw);
        if (String(parsed.metadata.generatedBy ?? '').trim() !== 'auto-observe-turn') {
          continue;
        }
        if (String(parsed.metadata.reviewStatus ?? '').trim().toLowerCase() === 'deprecated') {
          continue;
        }
        const commands = extractCommandCandidates(parsed.body);
        const checklist = extractChecklistItems(parsed.body);
        const toolsets = Array.isArray(parsed.metadata.toolsets)
          ? (parsed.metadata.toolsets as unknown[]).map((item) => String(item ?? '').trim()).filter(Boolean)
          : [];
        const platforms = Array.isArray(parsed.metadata.platforms)
          ? (parsed.metadata.platforms as unknown[]).map((item) => String(item ?? '').trim()).filter(Boolean)
          : [];
        const record: GovernanceSkillRecord = {
          id: path.resolve(targetPath),
          name: parsed.name || path.basename(current),
          targetPath: path.resolve(targetPath),
          workspaceDir,
          source: 'workspace',
          version: readSkillVersion(raw),
          reviewStatus: typeof parsed.metadata.reviewStatus === 'string' ? String(parsed.metadata.reviewStatus) : undefined,
          sourceFingerprint:
            typeof parsed.metadata.sourceFingerprint === 'string'
              ? String(parsed.metadata.sourceFingerprint)
              : undefined,
          generatedBy: typeof parsed.metadata.generatedBy === 'string' ? String(parsed.metadata.generatedBy) : undefined,
          generatedAt: typeof parsed.metadata.generatedAt === 'string' ? String(parsed.metadata.generatedAt) : undefined,
          toolsets,
          platforms,
          commands,
          checklist,
          normalizedBody: normalizeWorkflowText(parsed.body),
          summaryText: parsed.body.slice(0, 480),
        };
        items.set(record.id, record);
        continue;
      }
      for (const entry of entries) {
        if (entry.isDirectory()) {
          stack.push(path.join(current, entry.name));
        }
      }
    }
    return [...items.values()].sort((left, right) => left.targetPath.localeCompare(right.targetPath));
  }

  private detectCandidates(items: GovernanceSkillRecord[]): DetectionContext {
    const exactDuplicateIds = new Set<string>();
    const candidateDuplicateIds = new Set<string>();
    const nameConflictIds = new Set<string>();
    const boundaryFixIds = new Set<string>();
    const candidatePairs = new Map<string, Set<string>>();

    const byBody = new Map<string, GovernanceSkillRecord[]>();
    for (const item of items) {
      const key = item.normalizedBody;
      const bucket = byBody.get(key) ?? [];
      bucket.push(item);
      byBody.set(key, bucket);
      if (item.toolsets.length === 0 || item.platforms.length === 0) {
        boundaryFixIds.add(item.id);
      }
    }
    for (const group of byBody.values()) {
      if (group.length < 2) {
        continue;
      }
      for (const item of group) {
        exactDuplicateIds.add(item.id);
      }
      this.markPairs(candidatePairs, group.map((item) => item.id));
    }

    for (let index = 0; index < items.length; index += 1) {
      const left = items[index];
      for (let otherIndex = index + 1; otherIndex < items.length; otherIndex += 1) {
        const right = items[otherIndex];
        if (left.id === right.id) {
          continue;
        }
        if (left.name.trim().toLowerCase() === right.name.trim().toLowerCase() && left.normalizedBody !== right.normalizedBody) {
          nameConflictIds.add(left.id);
          nameConflictIds.add(right.id);
        }
        const sameFingerprint =
          left.sourceFingerprint &&
          right.sourceFingerprint &&
          left.sourceFingerprint.trim() === right.sourceFingerprint.trim();
        const similarWorkflow = similarityScore(left, right) >= 0.72;
        if (!sameFingerprint && !similarWorkflow) {
          continue;
        }
        candidateDuplicateIds.add(left.id);
        candidateDuplicateIds.add(right.id);
        this.markPairs(candidatePairs, [left.id, right.id]);
      }
    }

    for (const id of exactDuplicateIds) {
      candidateDuplicateIds.add(id);
    }

    return {
      exactDuplicateIds,
      candidateDuplicateIds,
      nameConflictIds,
      boundaryFixIds,
      candidatePairs,
    };
  }

  private async reviewInventory(
    items: GovernanceSkillRecord[],
    detection: DetectionContext
  ): Promise<{ fallback: boolean; fallbackReason?: string; items: LlmReviewItem[] }> {
    const llm = await this.getLlmClient();
    if (!llm) {
      return {
        fallback: true,
        fallbackReason: 'llm_unavailable',
        items: [],
      };
    }

    const reviewItems: LlmReviewItem[] = [];
    const workspaceBuckets = new Map<string, GovernanceSkillRecord[]>();
    for (const item of items) {
      const key = path.resolve(item.workspaceDir ?? '');
      const bucket = workspaceBuckets.get(key) ?? [];
      bucket.push(item);
      workspaceBuckets.set(key, bucket);
    }

    for (const bucketItems of workspaceBuckets.values()) {
      const candidateGroups = bucketItems
        .filter((item) => detection.candidateDuplicateIds.has(item.id))
        .map((item) => ({
          id: item.id,
          candidateIds: [...(detection.candidatePairs.get(item.id) ?? [])],
        }));
      const payload = {
        items: bucketItems.map((item) => ({
          id: item.id,
          name: item.name,
          targetPath: item.targetPath,
          version: item.version,
          sourceFingerprint: item.sourceFingerprint,
          toolsets: item.toolsets,
          platforms: item.platforms,
          commands: item.commands.slice(0, 8),
          checklist: item.checklist.slice(0, 8),
          bodySummary: item.summaryText,
          codeDetection: detection.exactDuplicateIds.has(item.id)
            ? 'exact_duplicate'
            : detection.candidateDuplicateIds.has(item.id)
              ? 'candidate_duplicate'
              : detection.nameConflictIds.has(item.id)
                ? 'name_conflict'
                : detection.boundaryFixIds.has(item.id)
                  ? 'boundary_fix_only'
                  : 'keep',
        })),
        candidateGroups,
      };
      const systemPrompt = [
        'You review auto-generated coding skills for duplicate governance.',
        'Return JSON only with shape {"items":[...]} and no markdown fences.',
        'Each item must include id, verdict, duplicateOfId, note.',
        'Allowed verdict values: keep, duplicate_of, keep_separate_conflict, needs_manual_review, boundary_fix_only.',
        'Only use duplicate_of when the skill is clearly redundant and the duplicateOfId is one of the provided candidateIds.',
        'If unsure, use keep or needs_manual_review.',
        'Name conflicts must not be auto-merged; prefer keep_separate_conflict.',
        'If the only issue is missing boundary metadata, use boundary_fix_only.',
      ].join('\n');
      try {
        const response = await llm.generate(
          [
            {
              role: 'user',
              content: `Review these auto-generated skills:\n${JSON.stringify(payload, null, 2)}`,
            },
          ],
          undefined,
          systemPrompt,
          {
            maxTokens: 2200,
            snapshotStage: 'initial',
          }
        );
        const extracted = extractJsonObject(response.content);
        if (!extracted) {
          return {
            fallback: true,
            fallbackReason: 'llm_response_missing_json',
            items: [],
          };
        }
        const parsed = JSON.parse(extracted) as { items?: Array<Record<string, unknown>> };
        const normalizedItems = Array.isArray(parsed.items) ? parsed.items : [];
        for (const item of normalizedItems) {
          const verdict = String(item.verdict ?? '').trim() as SkillGovernanceVerdict;
          reviewItems.push({
            id: String(item.id ?? '').trim(),
            verdict:
              verdict === 'duplicate_of' ||
              verdict === 'keep_separate_conflict' ||
              verdict === 'needs_manual_review' ||
              verdict === 'boundary_fix_only'
                ? verdict
                : 'keep',
            duplicateOfId: String(item.duplicateOfId ?? '').trim() || undefined,
            note: String(item.note ?? '').trim() || undefined,
          });
        }
      } catch (error) {
        return {
          fallback: true,
          fallbackReason: error instanceof Error ? error.message : String(error),
          items: [],
        };
      }
    }

    return {
      fallback: false,
      items: reviewItems,
    };
  }

  private buildReportItems(
    items: GovernanceSkillRecord[],
    detection: DetectionContext,
    llmItems: LlmReviewItem[]
  ): SkillGovernanceReportItem[] {
    const reviewById = new Map<string, LlmReviewItem>();
    for (const item of llmItems) {
      if (item.id) {
        reviewById.set(item.id, item);
      }
    }

    return items.map((item) => {
      const review = reviewById.get(item.id);
      const detectionValue: SkillGovernanceDetection = detection.exactDuplicateIds.has(item.id)
        ? 'exact_duplicate'
        : detection.candidateDuplicateIds.has(item.id)
          ? 'candidate_duplicate'
          : detection.nameConflictIds.has(item.id)
            ? 'name_conflict'
            : detection.boundaryFixIds.has(item.id)
              ? 'boundary_fix_only'
              : 'keep';
      let verdict: SkillGovernanceVerdict = review?.verdict ?? 'keep';
      let action: SkillGovernanceAction = 'none';
      let canonicalTargetPath: string | undefined;
      if (verdict === 'duplicate_of' && review?.duplicateOfId) {
        const allowedPairs = detection.candidatePairs.get(item.id);
        if (allowedPairs?.has(review.duplicateOfId) && review.duplicateOfId !== item.id) {
          const canonical = items.find((entry) => entry.id === review.duplicateOfId);
          canonicalTargetPath = canonical?.targetPath;
          if (canonicalTargetPath) {
            action = 'soft_archive';
          } else {
            verdict = 'needs_manual_review';
          }
        } else {
          verdict = 'needs_manual_review';
        }
      }
      if (verdict === 'boundary_fix_only' && detection.boundaryFixIds.has(item.id)) {
        action = 'boundary_backfill';
      }
      if (!review && (detectionValue === 'candidate_duplicate' || detectionValue === 'exact_duplicate')) {
        verdict = 'fallback_candidate';
      }
      return {
        id: item.id,
        name: item.name,
        targetPath: item.targetPath,
        workspaceDir: item.workspaceDir,
        detection: detectionValue,
        verdict,
        action,
        canonicalId: review?.duplicateOfId,
        canonicalTargetPath,
        note: review?.note,
      };
    });
  }

  private softArchiveSkill(item: GovernanceSkillRecord, canonicalTargetPath: string, governanceRunId: string): boolean {
    if (!fs.existsSync(item.targetPath)) {
      return false;
    }
    const currentContent = fs.readFileSync(item.targetPath, 'utf-8');
    const parsed = parseSkillMarkdown(currentContent);
    if (String(parsed.metadata.reviewStatus ?? '').trim().toLowerCase() === 'deprecated') {
      return false;
    }
    this.skillWriteStore.recordSkillRevision({
      skillName: item.name,
      targetPath: item.targetPath,
      workspaceDir: item.workspaceDir,
      version: readSkillVersion(currentContent),
      content: currentContent,
      sourceAction: 'governance',
    });
    const nextContent = upsertSkillMetadata(currentContent, {
      reviewStatus: 'deprecated',
      deprecatedReason: 'duplicate',
      deprecatedAt: nowIso(),
      replacedBy: canonicalTargetPath,
      governanceRunId,
      updatedAt: nowIso(),
    });
    fs.writeFileSync(item.targetPath, nextContent, 'utf-8');
    return true;
  }

  private markPairs(map: Map<string, Set<string>>, ids: string[]): void {
    for (const id of ids) {
      const bucket = map.get(id) ?? new Set<string>();
      for (const candidateId of ids) {
        if (candidateId !== id) {
          bucket.add(candidateId);
        }
      }
      map.set(id, bucket);
    }
  }

  private buildReport(input: {
    workspaceDir: string;
    runId: string;
    fallback: boolean;
    fallbackReason?: string;
    scannedSkills: number;
    exactDuplicates: number;
    candidateDuplicates: number;
    autoArchived: number;
    reportOnly: number;
    boundaryFixed: number;
    conflicts: number;
    items: SkillGovernanceReportItem[];
  }): WorkspaceSkillGovernanceReport {
    return {
      kind: 'workspace_skill_governance',
      runId: input.runId,
      workspaceDir: input.workspaceDir,
      generatedAt: nowIso(),
      fallback: input.fallback,
      fallbackReason: input.fallbackReason,
      summary: {
        scannedSkills: input.scannedSkills,
        exactDuplicates: input.exactDuplicates,
        candidateDuplicates: input.candidateDuplicates,
        autoArchived: input.autoArchived,
        reportOnly: input.reportOnly,
        boundaryFixed: input.boundaryFixed,
        conflicts: input.conflicts,
      },
      items: input.items,
    };
  }
}
