import type { LLMRuntime } from '../llm/index.js';
import type {
  SkillGovernanceVerdict,
} from '../types.js';
import type { SkillWriteStore } from './SkillWriteStore.js';

export interface AutoGeneratedSkillGovernanceServiceDeps {
  skillWriteStore: SkillWriteStore;
  getWorkspaceToolsetName: (workspaceDir?: string) => string | undefined;
  getLlmClient: () => Promise<LLMRuntime | null>;
  reloadSkills: () => void;
  publishWorkspaceGeneratedPack: (workspaceDir: string) => void;
  logger: {
    warn: (message: string) => void;
    info?: (message: string) => void;
  };
}

export interface GovernanceSkillRecord {
  id: string;
  name: string;
  targetPath: string;
  workspaceDir?: string;
  source: 'workspace';
  version?: string;
  reviewStatus?: string;
  sourceFingerprint?: string;
  generatedBy?: string;
  generatedAt?: string;
  toolsets: string[];
  platforms: string[];
  commands: string[];
  checklist: string[];
  normalizedBody: string;
  summaryText: string;
}

export interface DetectionContext {
  exactDuplicateIds: Set<string>;
  candidateDuplicateIds: Set<string>;
  nameConflictIds: Set<string>;
  boundaryFixIds: Set<string>;
  candidatePairs: Map<string, Set<string>>;
}

export interface LlmReviewItem {
  id: string;
  verdict: SkillGovernanceVerdict;
  duplicateOfId?: string;
  note?: string;
}
