import * as fs from 'node:fs';
import * as path from 'node:path';
import type { LLMRuntime } from '../llm/index.js';
import { getRuntimePlatformCapabilities } from '../runtime-platform.js';
import type {
  AutomationRunReport,
  SkillGovernanceAction,
  SkillGovernanceDetection,
  SkillGovernanceReportItem,
  SkillGovernanceVerdict,
} from '../types.js';
import {
  extractChecklistItems,
  extractCommandCandidates,
  normalizeWorkflowText,
  tokenizeWorkflowText,
} from '../utils/workflow-signal.js';
import type { SkillDraftRecord } from './SkillDraftStore.js';
import { SkillDraftStore } from './SkillDraftStore.js';
import { parseSkillMarkdown, readSkillVersion, upsertSkillMetadata } from './skill-markdown.js';

interface AutoGeneratedSkillGovernanceServiceDeps {
  skillDraftStore: SkillDraftStore;
  globalSkillsDir?: string;
  defaultWorkspaceDir: string;
  getWorkspaceToolsetName: (workspaceDir?: string) => string | undefined;
  getLlmClient: () => Promise<LLMRuntime | null>;
  reloadSkills: () => void;
  publishWorkspaceGeneratedPack: (workspaceDir: string) => void;
  logger: {
    warn: (message: string) => void;
    info?: (message: string) => void;
  };
}

interface GovernanceSkillRecord {
  id: string;
  name: string;
  targetPath: string;
  workspaceDir?: string;
  source: 'workspace' | 'global';
  version?: string;
  reviewStatus?: string;
  sourceFingerprint?: string;
  generatedBy?: string;
  generatedAt?: string;
  toolsets: string[];
  platforms: string[];
  commands: string[];
  checklist: string[];
  normalizedBody: string;
  summaryText: string;
}

interface DetectionContext {
  exactDuplicateIds: Set<string>;
  candidateDuplicateIds: Set<string>;
  nameConflictIds: Set<string>;
  boundaryFixIds: Set<string>;
  candidatePairs: Map<string, Set<string>>;
}

interface LlmReviewItem {
  id: string;
  verdict: SkillGovernanceVerdict;
  duplicateOfId?: string;
  note?: string;
}

function nowIso(): string {
  return new Date().toISOString();
}

function normalizePlatformMetadata(value: string | undefined): string[] {
  const normalized = String(value ?? '').trim().toLowerCase();
  if (normalized === 'win32' || normalized === 'windows') {
    return ['windows'];
  }
  if (normalized === 'darwin' || normalized === 'macos') {
    return ['macos'];
  }
  if (normalized === 'linux') {
    return ['linux'];
  }
  return [];
}

function extractJsonObject(raw: string): string | null {
  const source = String(raw ?? '').trim();
  const start = source.indexOf('{');
  const end = source.lastIndexOf('}');
  if (start < 0 || end <= start) {
    return null;
  }
  return source.slice(start, end + 1);
}

function similarityScore(left: GovernanceSkillRecord, right: GovernanceSkillRecord): number {
  const leftTokens = new Set(
    tokenizeWorkflowText(`${left.commands.join(' ')} ${left.checklist.join(' ')}`.trim()).slice(0, 48)
  );
  const rightTokens = new Set(
    tokenizeWorkflowText(`${right.commands.join(' ')} ${right.checklist.join(' ')}`.trim()).slice(0, 48)
  );
  if (leftTokens.size === 0 || rightTokens.size === 0) {
    return 0;
  }
  let intersection = 0;
  for (const token of leftTokens) {
    if (rightTokens.has(token)) {
      intersection += 1;
    }
  }
  const union = new Set([...leftTokens, ...rightTokens]).size;
  return union === 0 ? 0 : intersection / union;
}

function sortDraftsByRecency(records: SkillDraftRecord[]): SkillDraftRecord[] {
  return [...records].sort((left, right) => {
    const leftTime = String(left.reviewedAt ?? left.updatedAt ?? left.createdAt);
    const rightTime = String(right.reviewedAt ?? right.updatedAt ?? right.createdAt);
    return rightTime.localeCompare(leftTime);
  });
}

export class AutoGeneratedSkillGovernanceService {
  private readonly skillDraftStore: SkillDraftStore;
  private readonly globalSkillsDir?: string;
  private readonly defaultWorkspaceDir: string;
  private readonly getWorkspaceToolsetName: AutoGeneratedSkillGovernanceServiceDeps['getWorkspaceToolsetName'];
  private readonly getLlmClient: AutoGeneratedSkillGovernanceServiceDeps['getLlmClient'];
  private readonly reloadSkills: AutoGeneratedSkillGovernanceServiceDeps['reloadSkills'];
  private readonly publishWorkspaceGeneratedPack: AutoGeneratedSkillGovernanceServiceDeps['publishWorkspaceGeneratedPack'];
  private readonly logger: AutoGeneratedSkillGovernanceServiceDeps['logger'];

  constructor(deps: AutoGeneratedSkillGovernanceServiceDeps) {
    this.skillDraftStore = deps.skillDraftStore;
    this.globalSkillsDir = deps.globalSkillsDir ? path.resolve(deps.globalSkillsDir) : undefined;
    this.defaultWorkspaceDir = path.resolve(deps.defaultWorkspaceDir);
    this.getWorkspaceToolsetName = deps.getWorkspaceToolsetName;
    this.getLlmClient = deps.getLlmClient;
    this.reloadSkills = deps.reloadSkills;
    this.publishWorkspaceGeneratedPack = deps.publishWorkspaceGeneratedPack;
    this.logger = deps.logger;
  }

  async run(input: {
    jobId: string;
    runId: string;
    workspaceDir?: string;
  }): Promise<AutomationRunReport> {
    const workspaceDir = input.workspaceDir ? path.resolve(input.workspaceDir) : this.defaultWorkspaceDir;
    const backfill = this.backfillMetadata(workspaceDir);
    const inventory = this.scanAutoGeneratedSkills(workspaceDir);
    if (inventory.length === 0) {
      return {
        kind: 'auto_generated_skill_governance',
        jobId: input.jobId,
        runId: input.runId,
        generatedAt: nowIso(),
        fallback: false,
        summary: {
          scannedSkills: 0,
          exactDuplicates: 0,
          candidateDuplicates: 0,
          autoArchived: 0,
          reportOnly: 0,
          boundaryFixed: backfill.boundaryFixedCount,
          conflicts: 0,
        },
        items: [],
      };
    }

    const detection = this.detectCandidates(inventory);
    const review = await this.reviewInventory(inventory, detection);
    const items = this.buildReportItems(inventory, detection, review.items);
    let autoArchived = 0;
    const touchedWorkspaces = new Set<string>();

    if (!review.fallback) {
      for (const item of items) {
        if (item.action !== 'soft_archive' || !item.canonicalTargetPath) {
          continue;
        }
        const skill = inventory.find((entry) => entry.id === item.id);
        if (!skill) {
          continue;
        }
        if (this.softArchiveSkill(skill, item.canonicalTargetPath, input.runId)) {
          autoArchived += 1;
          if (skill.workspaceDir) {
            touchedWorkspaces.add(skill.workspaceDir);
          }
        }
      }
    }

    if (autoArchived > 0 || backfill.provenanceBackfillCount > 0) {
      this.reloadSkills();
    }
    for (const workspace of touchedWorkspaces) {
      this.publishWorkspaceGeneratedPack(workspace);
    }

    return {
      kind: 'auto_generated_skill_governance',
      jobId: input.jobId,
      runId: input.runId,
      generatedAt: nowIso(),
      fallback: review.fallback,
      fallbackReason: review.fallbackReason,
      summary: {
        scannedSkills: inventory.length,
        exactDuplicates: detection.exactDuplicateIds.size,
        candidateDuplicates: detection.candidateDuplicateIds.size,
        autoArchived,
        reportOnly: items.filter((item) => item.action === 'none' && item.verdict !== 'keep').length,
        boundaryFixed: backfill.boundaryFixedCount,
        conflicts: items.filter(
          (item) =>
            item.verdict === 'keep_separate_conflict' ||
            item.verdict === 'needs_manual_review' ||
            item.detection === 'name_conflict'
        ).length,
      },
      items,
    };
  }

  private backfillMetadata(seedWorkspaceDir: string): {
    boundaryFixedCount: number;
    provenanceBackfillCount: number;
  } {
    const drafts = sortDraftsByRecency(
      this.skillDraftStore.listDrafts({
        status: 'approved',
        reason: 'repeated_success_pattern',
      })
    );
    const latestByPath = new Map<string, SkillDraftRecord>();
    for (const draft of drafts) {
      const key = path.resolve(draft.targetPath);
      if (!latestByPath.has(key)) {
        latestByPath.set(key, draft);
      }
    }

    let boundaryFixedCount = 0;
    let provenanceBackfillCount = 0;
    for (const record of latestByPath.values()) {
      if (!fs.existsSync(record.targetPath)) {
        continue;
      }
      const currentContent = fs.readFileSync(record.targetPath, 'utf-8');
      const parsed = parseSkillMarkdown(currentContent);
      const patch: Record<string, unknown> = {};
      let changed = false;
      let boundaryChanged = false;
      if (String(parsed.metadata.generatedBy ?? '').trim() !== 'auto-observe-turn') {
        patch.generatedBy = 'auto-observe-turn';
        changed = true;
        provenanceBackfillCount += 1;
      }
      if (String(parsed.metadata.generationReason ?? '').trim() !== 'repeated_success_pattern') {
        patch.generationReason = 'repeated_success_pattern';
        changed = true;
      }
      if (!String(parsed.metadata.sourceFingerprint ?? '').trim() && record.sourceFingerprint) {
        patch.sourceFingerprint = record.sourceFingerprint;
        changed = true;
      }
      if (!String(parsed.metadata.sourceSessionId ?? '').trim() && record.sourceSessionId) {
        patch.sourceSessionId = record.sourceSessionId;
        changed = true;
      }
      if (!String(parsed.metadata.originToolset ?? '').trim() && record.originToolset) {
        patch.originToolset = record.originToolset;
        changed = true;
      }
      if (!String(parsed.metadata.originPlatform ?? '').trim() && record.originPlatform) {
        patch.originPlatform = record.originPlatform;
        changed = true;
      }
      if (!String(parsed.metadata.generatedAt ?? '').trim()) {
        patch.generatedAt = record.generatedAt ?? record.reviewedAt ?? record.updatedAt ?? record.createdAt;
        changed = true;
      }

      const existingToolsets = Array.isArray(parsed.metadata.toolsets)
        ? (parsed.metadata.toolsets as unknown[]).map((item) => String(item ?? '').trim()).filter(Boolean)
        : [];
      if (existingToolsets.length === 0) {
        const fallbackToolset =
          record.originToolset ||
          this.getWorkspaceToolsetName(record.workspaceDir || seedWorkspaceDir) ||
          'full-access';
        patch.toolsets = [fallbackToolset];
        changed = true;
        boundaryChanged = true;
      }
      const existingPlatforms = Array.isArray(parsed.metadata.platforms)
        ? (parsed.metadata.platforms as unknown[]).map((item) => String(item ?? '').trim()).filter(Boolean)
        : [];
      if (existingPlatforms.length === 0) {
        const fallbackPlatformsFromRecord = normalizePlatformMetadata(record.originPlatform);
        const fallbackPlatforms =
          fallbackPlatformsFromRecord.length > 0
            ? fallbackPlatformsFromRecord
            : normalizePlatformMetadata(getRuntimePlatformCapabilities().platform);
        patch.platforms = fallbackPlatforms.length > 0 ? fallbackPlatforms : ['windows'];
        changed = true;
        boundaryChanged = true;
      }

      if (!changed) {
        continue;
      }
      fs.writeFileSync(record.targetPath, upsertSkillMetadata(currentContent, patch), 'utf-8');
      if (boundaryChanged) {
        boundaryFixedCount += 1;
      }
    }

    return {
      boundaryFixedCount,
      provenanceBackfillCount,
    };
  }

  private scanAutoGeneratedSkills(seedWorkspaceDir: string): GovernanceSkillRecord[] {
    const roots = new Map<string, { source: 'workspace' | 'global'; workspaceDir?: string }>();
    roots.set(path.join(seedWorkspaceDir, 'skills'), {
      source: 'workspace',
      workspaceDir: seedWorkspaceDir,
    });
    for (const draft of this.skillDraftStore.listDrafts({
      status: 'approved',
      reason: 'repeated_success_pattern',
    })) {
      if (draft.workspaceDir) {
        roots.set(path.join(path.resolve(draft.workspaceDir), 'skills'), {
          source: 'workspace',
          workspaceDir: path.resolve(draft.workspaceDir),
        });
      }
    }
    if (this.globalSkillsDir) {
      roots.set(this.globalSkillsDir, {
        source: 'global',
      });
    }

    const items = new Map<string, GovernanceSkillRecord>();
    for (const [rootDir, meta] of roots.entries()) {
      if (!fs.existsSync(rootDir)) {
        continue;
      }
      const stack = [rootDir];
      while (stack.length > 0) {
        const current = stack.pop();
        if (!current || !fs.existsSync(current)) {
          continue;
        }
        const entries = fs.readdirSync(current, { withFileTypes: true });
        const skillFile = entries.find((entry) => entry.isFile() && entry.name.toLowerCase() === 'skill.md');
        if (skillFile) {
          const targetPath = path.join(current, skillFile.name);
          const raw = fs.readFileSync(targetPath, 'utf-8');
          const parsed = parseSkillMarkdown(raw);
          if (String(parsed.metadata.generatedBy ?? '').trim() !== 'auto-observe-turn') {
            continue;
          }
          if (String(parsed.metadata.reviewStatus ?? '').trim().toLowerCase() === 'deprecated') {
            continue;
          }
          const commands = extractCommandCandidates(parsed.body);
          const checklist = extractChecklistItems(parsed.body);
          const toolsets = Array.isArray(parsed.metadata.toolsets)
            ? (parsed.metadata.toolsets as unknown[]).map((item) => String(item ?? '').trim()).filter(Boolean)
            : [];
          const platforms = Array.isArray(parsed.metadata.platforms)
            ? (parsed.metadata.platforms as unknown[]).map((item) => String(item ?? '').trim()).filter(Boolean)
            : [];
          const record: GovernanceSkillRecord = {
            id: path.resolve(targetPath),
            name: parsed.name || path.basename(current),
            targetPath: path.resolve(targetPath),
            workspaceDir: meta.workspaceDir,
            source: meta.source,
            version: readSkillVersion(raw),
            reviewStatus: typeof parsed.metadata.reviewStatus === 'string' ? String(parsed.metadata.reviewStatus) : undefined,
            sourceFingerprint:
              typeof parsed.metadata.sourceFingerprint === 'string'
                ? String(parsed.metadata.sourceFingerprint)
                : undefined,
            generatedBy: typeof parsed.metadata.generatedBy === 'string' ? String(parsed.metadata.generatedBy) : undefined,
            generatedAt: typeof parsed.metadata.generatedAt === 'string' ? String(parsed.metadata.generatedAt) : undefined,
            toolsets,
            platforms,
            commands,
            checklist,
            normalizedBody: normalizeWorkflowText(parsed.body),
            summaryText: parsed.body.slice(0, 480),
          };
          items.set(record.id, record);
          continue;
        }
        for (const entry of entries) {
          if (entry.isDirectory()) {
            stack.push(path.join(current, entry.name));
          }
        }
      }
    }
    return [...items.values()].sort((left, right) => left.targetPath.localeCompare(right.targetPath));
  }

  private detectCandidates(items: GovernanceSkillRecord[]): DetectionContext {
    const exactDuplicateIds = new Set<string>();
    const candidateDuplicateIds = new Set<string>();
    const nameConflictIds = new Set<string>();
    const boundaryFixIds = new Set<string>();
    const candidatePairs = new Map<string, Set<string>>();

    const byBody = new Map<string, GovernanceSkillRecord[]>();
    for (const item of items) {
      const key = item.normalizedBody;
      const bucket = byBody.get(key) ?? [];
      bucket.push(item);
      byBody.set(key, bucket);
      if (item.toolsets.length === 0 || item.platforms.length === 0) {
        boundaryFixIds.add(item.id);
      }
    }
    for (const group of byBody.values()) {
      if (group.length < 2) {
        continue;
      }
      for (const item of group) {
        exactDuplicateIds.add(item.id);
      }
      this.markPairs(candidatePairs, group.map((item) => item.id));
    }

    for (let index = 0; index < items.length; index += 1) {
      const left = items[index];
      for (let otherIndex = index + 1; otherIndex < items.length; otherIndex += 1) {
        const right = items[otherIndex];
        if (left.id === right.id) {
          continue;
        }
        if (left.name.trim().toLowerCase() === right.name.trim().toLowerCase() && left.normalizedBody !== right.normalizedBody) {
          nameConflictIds.add(left.id);
          nameConflictIds.add(right.id);
        }
        const sameFingerprint =
          left.sourceFingerprint &&
          right.sourceFingerprint &&
          left.sourceFingerprint.trim() === right.sourceFingerprint.trim();
        const similarWorkflow = similarityScore(left, right) >= 0.72;
        if (!sameFingerprint && !similarWorkflow) {
          continue;
        }
        candidateDuplicateIds.add(left.id);
        candidateDuplicateIds.add(right.id);
        this.markPairs(candidatePairs, [left.id, right.id]);
      }
    }

    for (const id of exactDuplicateIds) {
      candidateDuplicateIds.add(id);
    }

    return {
      exactDuplicateIds,
      candidateDuplicateIds,
      nameConflictIds,
      boundaryFixIds,
      candidatePairs,
    };
  }

  private async reviewInventory(
    items: GovernanceSkillRecord[],
    detection: DetectionContext
  ): Promise<{ fallback: boolean; fallbackReason?: string; items: LlmReviewItem[] }> {
    const llm = await this.getLlmClient();
    if (!llm) {
      return {
        fallback: true,
        fallbackReason: 'llm_unavailable',
        items: [],
      };
    }

    const reviewItems: LlmReviewItem[] = [];
    const workspaceBuckets = new Map<string, GovernanceSkillRecord[]>();
    for (const item of items) {
      const key = item.workspaceDir ? path.resolve(item.workspaceDir) : '__global__';
      const bucket = workspaceBuckets.get(key) ?? [];
      bucket.push(item);
      workspaceBuckets.set(key, bucket);
    }

    for (const bucketItems of workspaceBuckets.values()) {
      const candidateGroups = bucketItems
        .filter((item) => detection.candidateDuplicateIds.has(item.id))
        .map((item) => ({
          id: item.id,
          candidateIds: [...(detection.candidatePairs.get(item.id) ?? [])],
        }));
      const payload = {
        items: bucketItems.map((item) => ({
          id: item.id,
          name: item.name,
          targetPath: item.targetPath,
          version: item.version,
          sourceFingerprint: item.sourceFingerprint,
          toolsets: item.toolsets,
          platforms: item.platforms,
          commands: item.commands.slice(0, 8),
          checklist: item.checklist.slice(0, 8),
          bodySummary: item.summaryText,
          codeDetection: detection.exactDuplicateIds.has(item.id)
            ? 'exact_duplicate'
            : detection.candidateDuplicateIds.has(item.id)
              ? 'candidate_duplicate'
              : detection.nameConflictIds.has(item.id)
                ? 'name_conflict'
                : detection.boundaryFixIds.has(item.id)
                  ? 'boundary_fix_only'
                  : 'keep',
        })),
        candidateGroups,
      };
      const systemPrompt = [
        'You review auto-generated coding skills for duplicate governance.',
        'Return JSON only with shape {"items":[...]} and no markdown fences.',
        'Each item must include id, verdict, duplicateOfId, note.',
        'Allowed verdict values: keep, duplicate_of, keep_separate_conflict, needs_manual_review, boundary_fix_only.',
        'Only use duplicate_of when the skill is clearly redundant and the duplicateOfId is one of the provided candidateIds.',
        'If unsure, use keep or needs_manual_review.',
        'Name conflicts must not be auto-merged; prefer keep_separate_conflict.',
        'If the only issue is missing boundary metadata, use boundary_fix_only.',
      ].join('\n');
      try {
        const response = await llm.generate(
          [
            {
              role: 'user',
              content: `Review these auto-generated skills:\n${JSON.stringify(payload, null, 2)}`,
            },
          ],
          undefined,
          systemPrompt,
          {
            maxTokens: 2200,
            snapshotStage: 'initial',
          }
        );
        const extracted = extractJsonObject(response.content);
        if (!extracted) {
          return {
            fallback: true,
            fallbackReason: 'llm_response_missing_json',
            items: [],
          };
        }
        const parsed = JSON.parse(extracted) as { items?: Array<Record<string, unknown>> };
        const normalizedItems = Array.isArray(parsed.items) ? parsed.items : [];
        for (const item of normalizedItems) {
          const verdict = String(item.verdict ?? '').trim() as SkillGovernanceVerdict;
          reviewItems.push({
            id: String(item.id ?? '').trim(),
            verdict:
              verdict === 'duplicate_of' ||
              verdict === 'keep_separate_conflict' ||
              verdict === 'needs_manual_review' ||
              verdict === 'boundary_fix_only'
                ? verdict
                : 'keep',
            duplicateOfId: String(item.duplicateOfId ?? '').trim() || undefined,
            note: String(item.note ?? '').trim() || undefined,
          });
        }
      } catch (error) {
        return {
          fallback: true,
          fallbackReason: error instanceof Error ? error.message : String(error),
          items: [],
        };
      }
    }

    return {
      fallback: false,
      items: reviewItems,
    };
  }

  private buildReportItems(
    items: GovernanceSkillRecord[],
    detection: DetectionContext,
    llmItems: LlmReviewItem[]
  ): SkillGovernanceReportItem[] {
    const reviewById = new Map<string, LlmReviewItem>();
    for (const item of llmItems) {
      if (item.id) {
        reviewById.set(item.id, item);
      }
    }

    return items.map((item) => {
      const review = reviewById.get(item.id);
      const detectionValue: SkillGovernanceDetection = detection.exactDuplicateIds.has(item.id)
        ? 'exact_duplicate'
        : detection.candidateDuplicateIds.has(item.id)
          ? 'candidate_duplicate'
          : detection.nameConflictIds.has(item.id)
            ? 'name_conflict'
            : detection.boundaryFixIds.has(item.id)
              ? 'boundary_fix_only'
              : 'keep';
      let verdict: SkillGovernanceVerdict = review?.verdict ?? 'keep';
      let action: SkillGovernanceAction = 'none';
      let canonicalTargetPath: string | undefined;
      if (verdict === 'duplicate_of' && review?.duplicateOfId) {
        const allowedPairs = detection.candidatePairs.get(item.id);
        if (allowedPairs?.has(review.duplicateOfId) && review.duplicateOfId !== item.id) {
          const canonical = items.find((entry) => entry.id === review.duplicateOfId);
          canonicalTargetPath = canonical?.targetPath;
          if (canonicalTargetPath) {
            action = 'soft_archive';
          } else {
            verdict = 'needs_manual_review';
          }
        } else {
          verdict = 'needs_manual_review';
        }
      }
      if (verdict === 'boundary_fix_only' && detection.boundaryFixIds.has(item.id)) {
        action = 'boundary_backfill';
      }
      if (!review && (detectionValue === 'candidate_duplicate' || detectionValue === 'exact_duplicate')) {
        verdict = 'fallback_candidate';
      }
      return {
        id: item.id,
        name: item.name,
        targetPath: item.targetPath,
        workspaceDir: item.workspaceDir,
        detection: detectionValue,
        verdict,
        action,
        canonicalId: review?.duplicateOfId,
        canonicalTargetPath,
        note: review?.note,
      };
    });
  }

  private softArchiveSkill(item: GovernanceSkillRecord, canonicalTargetPath: string, governanceRunId: string): boolean {
    if (!fs.existsSync(item.targetPath)) {
      return false;
    }
    const currentContent = fs.readFileSync(item.targetPath, 'utf-8');
    const parsed = parseSkillMarkdown(currentContent);
    if (String(parsed.metadata.reviewStatus ?? '').trim().toLowerCase() === 'deprecated') {
      return false;
    }
    this.skillDraftStore.recordSkillRevision({
      skillName: item.name,
      targetPath: item.targetPath,
      workspaceDir: item.workspaceDir,
      version: readSkillVersion(currentContent),
      content: currentContent,
      sourceAction: 'governance',
    });
    const nextContent = upsertSkillMetadata(currentContent, {
      reviewStatus: 'deprecated',
      deprecatedReason: 'duplicate',
      deprecatedAt: nowIso(),
      replacedBy: canonicalTargetPath,
      governanceRunId,
      updatedAt: nowIso(),
    });
    fs.writeFileSync(item.targetPath, nextContent, 'utf-8');
    return true;
  }

  private markPairs(map: Map<string, Set<string>>, ids: string[]): void {
    for (const id of ids) {
      const bucket = map.get(id) ?? new Set<string>();
      for (const candidateId of ids) {
        if (candidateId !== id) {
          bucket.add(candidateId);
        }
      }
      map.set(id, bucket);
    }
  }
}
