import * as assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { AutoGeneratedSkillGovernanceService, SkillDraftStore } from '../../src/skills/index.js';
import { parseSkillMarkdown, renderSkillMarkdown } from '../../src/skills/skill-markdown.js';

function createHarness(): {
  tempDir: string;
  workspaceDir: string;
  globalSkillsDir: string;
  runtimeSkillsDir: string;
  store: SkillDraftStore;
} {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'auto-skill-governance-'));
  const workspaceDir = path.join(tempDir, 'workspace');
  const globalSkillsDir = path.join(tempDir, 'global-skills');
  const runtimeSkillsDir = path.join(tempDir, 'runtime-skills');
  fs.mkdirSync(workspaceDir, { recursive: true });
  fs.mkdirSync(globalSkillsDir, { recursive: true });
  fs.mkdirSync(runtimeSkillsDir, { recursive: true });
  return {
    tempDir,
    workspaceDir,
    globalSkillsDir,
    runtimeSkillsDir,
    store: new SkillDraftStore(runtimeSkillsDir),
  };
}

function cleanupHarness(tempDir: string): void {
  fs.rmSync(tempDir, { recursive: true, force: true });
}

function writeSkillFile(input: {
  workspaceDir: string;
  slug: string;
  name: string;
  metadata?: Record<string, unknown>;
  body: string;
}): string {
  const targetPath = path.join(input.workspaceDir, 'skills', input.slug, 'SKILL.md');
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(
    targetPath,
    renderSkillMarkdown({
      name: input.name,
      description: `Generated workflow ${input.name}`,
      metadata: input.metadata,
      body: input.body,
    }),
    'utf-8'
  );
  return targetPath;
}

function markDraftApproved(runtimeSkillsDir: string, draftId: string): void {
  const draftPath = path.join(runtimeSkillsDir, 'pending', `${draftId}.json`);
  const record = JSON.parse(fs.readFileSync(draftPath, 'utf-8')) as Record<string, unknown>;
  record.status = 'approved';
  record.reviewedAt = '2026-04-20T00:00:00.000Z';
  record.updatedAt = '2026-04-20T00:00:00.000Z';
  fs.writeFileSync(draftPath, JSON.stringify(record, null, 2), 'utf-8');
}

async function testGovernanceBackfillsAndArchivesDuplicates(): Promise<void> {
  const harness = createHarness();
  try {
    const duplicateBody = [
      'When the user asks for this repeated workflow, follow these steps.',
      '',
      '## Workflow',
      '1. `npm run build:web`',
      '2. `npm test`',
      '',
      '## Notes',
      '- Publish after checks',
    ].join('\n');
    const controlBody = [
      'When the user asks for a similar but distinct workflow, follow these steps.',
      '',
      '## Workflow',
      '1. `npm run build:web`',
      '2. `npm run lint`',
      '3. `npm test`',
      '',
      '## Notes',
      '- Keep linting separate from publish',
    ].join('\n');

    const canonicalPath = writeSkillFile({
      workspaceDir: harness.workspaceDir,
      slug: 'workflow-build-release',
      name: 'workflow-build-release',
      metadata: {
        reviewStatus: 'approved',
        version: '1',
        source: 'workspace',
        generatedBy: 'auto-observe-turn',
        generationReason: 'repeated_success_pattern',
        sourceFingerprint: 'build-release',
        sourceSessionId: 'sess-a',
        originToolset: 'full-access',
        originPlatform: 'win32',
        generatedAt: '2026-04-19T00:00:00.000Z',
        toolsets: ['full-access'],
        platforms: ['windows'],
      },
      body: duplicateBody,
    });
    const duplicatePath = writeSkillFile({
      workspaceDir: harness.workspaceDir,
      slug: 'workflow-build-release-copy',
      name: 'workflow-build-release-copy',
      metadata: {
        reviewStatus: 'approved',
        version: '1',
        source: 'workspace',
        generatedBy: 'auto-observe-turn',
        generationReason: 'repeated_success_pattern',
        sourceFingerprint: 'build-release-copy',
        sourceSessionId: 'sess-b',
        originToolset: 'full-access',
        originPlatform: 'win32',
        generatedAt: '2026-04-19T01:00:00.000Z',
        toolsets: ['full-access'],
        platforms: ['windows'],
      },
      body: duplicateBody,
    });
    const controlPath = writeSkillFile({
      workspaceDir: harness.workspaceDir,
      slug: 'workflow-build-lint',
      name: 'workflow-build-lint',
      metadata: {
        reviewStatus: 'approved',
        version: '1',
        source: 'workspace',
        generatedBy: 'auto-observe-turn',
        generationReason: 'repeated_success_pattern',
        sourceFingerprint: 'build-lint',
        sourceSessionId: 'sess-c',
        originToolset: 'full-access',
        originPlatform: 'win32',
        generatedAt: '2026-04-19T02:00:00.000Z',
        toolsets: ['full-access'],
        platforms: ['windows'],
      },
      body: controlBody,
    });
    const backfillPath = writeSkillFile({
      workspaceDir: harness.workspaceDir,
      slug: 'workflow-legacy-backfill',
      name: 'workflow-legacy-backfill',
      metadata: {
        reviewStatus: 'approved',
        version: '1',
        source: 'workspace',
      },
      body: [
        'When the user asks for the old release checklist, follow these steps.',
        '',
        '## Workflow',
        '1. `npm run build:web`',
        '2. `npm run pack`',
      ].join('\n'),
    });

    const draft = harness.store.createDraft({
      name: 'workflow-legacy-backfill',
      description: 'Legacy generated workflow',
      content: fs.readFileSync(backfillPath, 'utf-8'),
      action: 'update',
      target: 'workspace',
      workspaceDir: harness.workspaceDir,
      sourceSessionId: 'sess-legacy',
      reason: 'repeated_success_pattern',
      sourceFingerprint: 'legacy-pack',
      originToolset: 'full-access',
      originPlatform: 'win32',
      generatedAt: '2026-04-18T00:00:00.000Z',
    });
    markDraftApproved(harness.runtimeSkillsDir, draft.id);

    let reloadCount = 0;
    const publishedWorkspaces: string[] = [];
    const service = new AutoGeneratedSkillGovernanceService({
      skillDraftStore: harness.store,
      globalSkillsDir: harness.globalSkillsDir,
      defaultWorkspaceDir: harness.workspaceDir,
      getWorkspaceToolsetName: () => 'full-access',
      getLlmClient: async () =>
        ({
          generate: async () => ({
            content: JSON.stringify({
              items: [
                {
                  id: canonicalPath,
                  verdict: 'keep',
                  note: 'Canonical release workflow.',
                },
                {
                  id: duplicatePath,
                  verdict: 'duplicate_of',
                  duplicateOfId: canonicalPath,
                  note: 'Same workflow as canonical release skill.',
                },
                {
                  id: controlPath,
                  verdict: 'keep',
                  note: 'Distinct lint-aware workflow.',
                },
                {
                  id: backfillPath,
                  verdict: 'boundary_fix_only',
                  note: 'Metadata backfill only.',
                },
              ],
            }),
          }),
        }) as any,
      reloadSkills: () => {
        reloadCount += 1;
      },
      publishWorkspaceGeneratedPack: (workspaceDir) => {
        publishedWorkspaces.push(path.resolve(workspaceDir));
      },
      logger: { warn: () => undefined },
    });

    const report = await service.run({
      jobId: 'automation-governance',
      runId: 'run-1',
      workspaceDir: harness.workspaceDir,
    });

    assert.equal(report.fallback, false);
    assert.equal(report.summary.scannedSkills, 4);
    assert.equal(report.summary.exactDuplicates, 2);
    assert.equal(report.summary.autoArchived, 1);
    assert.equal(report.summary.boundaryFixed, 1);
    assert.equal(reloadCount, 1);
    assert.deepEqual(publishedWorkspaces, [path.resolve(harness.workspaceDir)]);

    const canonicalParsed = parseSkillMarkdown(fs.readFileSync(canonicalPath, 'utf-8'));
    assert.equal(canonicalParsed.metadata.reviewStatus, 'approved');

    const duplicateParsed = parseSkillMarkdown(fs.readFileSync(duplicatePath, 'utf-8'));
    assert.equal(duplicateParsed.metadata.reviewStatus, 'deprecated');
    assert.equal(duplicateParsed.metadata.deprecatedReason, 'duplicate');
    assert.equal(duplicateParsed.metadata.replacedBy, canonicalPath);
    assert.equal(duplicateParsed.metadata.governanceRunId, 'run-1');

    const backfillParsed = parseSkillMarkdown(fs.readFileSync(backfillPath, 'utf-8'));
    assert.equal(backfillParsed.metadata.generatedBy, 'auto-observe-turn');
    assert.equal(backfillParsed.metadata.generationReason, 'repeated_success_pattern');
    assert.equal(backfillParsed.metadata.originToolset, 'full-access');
    assert.equal(backfillParsed.metadata.originPlatform, 'win32');
    assert.deepEqual(backfillParsed.metadata.toolsets, ['full-access']);
    assert.deepEqual(backfillParsed.metadata.platforms, ['windows']);

    const history = harness.store.listHistory({ targetPath: duplicatePath, workspaceDir: harness.workspaceDir });
    assert.equal(history[0]?.sourceAction, 'governance');
  } finally {
    cleanupHarness(harness.tempDir);
  }
}

async function testGovernanceFallbackLeavesSkillsUntouched(): Promise<void> {
  const harness = createHarness();
  try {
    const body = [
      'When the user asks for this repeated workflow, follow these steps.',
      '',
      '## Workflow',
      '1. `npm run build:web`',
      '2. `npm test`',
    ].join('\n');
    const canonicalPath = writeSkillFile({
      workspaceDir: harness.workspaceDir,
      slug: 'workflow-one',
      name: 'workflow-one',
      metadata: {
        reviewStatus: 'approved',
        version: '1',
        source: 'workspace',
        generatedBy: 'auto-observe-turn',
        generationReason: 'repeated_success_pattern',
        sourceFingerprint: 'same-workflow-a',
        toolsets: ['full-access'],
        platforms: ['windows'],
      },
      body,
    });
    const duplicatePath = writeSkillFile({
      workspaceDir: harness.workspaceDir,
      slug: 'workflow-two',
      name: 'workflow-two',
      metadata: {
        reviewStatus: 'approved',
        version: '1',
        source: 'workspace',
        generatedBy: 'auto-observe-turn',
        generationReason: 'repeated_success_pattern',
        sourceFingerprint: 'same-workflow-b',
        toolsets: ['full-access'],
        platforms: ['windows'],
      },
      body,
    });

    let published = false;
    const service = new AutoGeneratedSkillGovernanceService({
      skillDraftStore: harness.store,
      globalSkillsDir: harness.globalSkillsDir,
      defaultWorkspaceDir: harness.workspaceDir,
      getWorkspaceToolsetName: () => 'full-access',
      getLlmClient: async () => null,
      reloadSkills: () => undefined,
      publishWorkspaceGeneratedPack: () => {
        published = true;
      },
      logger: { warn: () => undefined },
    });

    const report = await service.run({
      jobId: 'automation-governance',
      runId: 'run-fallback',
      workspaceDir: harness.workspaceDir,
    });

    assert.equal(report.fallback, true);
    assert.equal(report.fallbackReason, 'llm_unavailable');
    assert.equal(report.summary.autoArchived, 0);
    assert.equal(published, false);

    const duplicateParsed = parseSkillMarkdown(fs.readFileSync(duplicatePath, 'utf-8'));
    assert.equal(duplicateParsed.metadata.reviewStatus, 'approved');
    assert.equal(duplicateParsed.metadata.replacedBy, undefined);

    const candidateItem = report.items.find((item) => item.id === duplicatePath);
    assert.equal(candidateItem?.verdict, 'fallback_candidate');
    assert.ok(report.items.some((item) => item.id === canonicalPath));
  } finally {
    cleanupHarness(harness.tempDir);
  }
}

async function runAll(): Promise<void> {
  await testGovernanceBackfillsAndArchivesDuplicates();
  await testGovernanceFallbackLeavesSkillsUntouched();
  console.log('auto-generated-skill-governance tests passed');
}

runAll().catch((error) => {
  console.error(error);
  process.exit(1);
});
