import * as fs from 'node:fs';
import * as path from 'node:path';
import type { Request, Response } from 'express';
import type { SkillCatalogEntry } from '../../skills/SkillLoader.js';
import {
  type WebServerRouteRegistrationDependencies,
} from './web-server-route-contracts.js';
import { rejectObserveOnlyIfNeeded } from './web-server-route-guards.js';
import { resolveGovernanceRouteContext } from './web-server-governance-context.js';

function isPathInside(parentDir: string, childPath: string): boolean {
  const relative = path.relative(path.resolve(parentDir), path.resolve(childPath));
  return Boolean(relative) && !relative.startsWith('..') && !path.isAbsolute(relative);
}

function isWorkspaceSkill(workspaceDir: string, skill: SkillCatalogEntry): boolean {
  if (skill.source !== 'workspace') {
    return false;
  }
  return isPathInside(path.join(workspaceDir, 'skills'), skill.path);
}

function toWorkspaceSkillView(workspaceDir: string, skill: SkillCatalogEntry) {
  const content = fs.existsSync(skill.path) ? fs.readFileSync(skill.path, 'utf-8') : '';
  return {
    name: skill.name,
    description: skill.description,
    path: skill.path,
    version: skill.version,
    reviewStatus: skill.reviewStatus,
    isAutoGenerated: String(skill.metadata?.generatedBy ?? '').trim() === 'auto-observe-turn',
    metadata: skill.metadata,
    content,
    workspaceDir,
  };
}

function listWorkspaceSkills(
  deps: WebServerRouteRegistrationDependencies,
  workspaceDir: string
) {
  return deps.agent
    .getSkillLoader()
    .getSkillCatalog({
      workspaceDir,
      includeGlobalSkills: false,
      includeWorkspaceSkills: true,
      includePackSkills: false,
      includeDeprecated: true,
    })
    .filter((skill) => isWorkspaceSkill(workspaceDir, skill))
    .map((skill) => toWorkspaceSkillView(workspaceDir, skill));
}

function appendSkillGovernanceAudit(
  deps: WebServerRouteRegistrationDependencies,
  input: {
    sessionId?: string;
    workspaceDir: string;
    report: Awaited<ReturnType<WebServerRouteRegistrationDependencies['governanceServices']['runWorkspaceSkillGovernance']>>;
  }
): void {
  deps.agent.getGovernanceAuditStore().append({
    kind: 'skill_governance_run',
    title: 'Workspace skill governance completed',
    detail: `scanned=${input.report.summary.scannedSkills}, archived=${input.report.summary.autoArchived}, fallback=${input.report.fallback}`,
    sessionId: input.sessionId,
    workspaceDir: input.workspaceDir,
    entityType: 'skill',
    status: input.report.summary.autoArchived > 0 || input.report.fallback ? 'warning' : 'success',
    metadata: {
      runId: input.report.runId,
      scannedSkills: input.report.summary.scannedSkills,
      autoArchived: input.report.summary.autoArchived,
      fallback: input.report.fallback,
      fallbackReason: input.report.fallbackReason,
    },
  });
}

export function registerWorkspaceGovernanceRoutes(
  deps: WebServerRouteRegistrationDependencies
): void {
  deps.app.get('/api/governance/workspace', (req: Request, res: Response) => {
    try {
      const resolved = resolveGovernanceRouteContext(deps, req.query.sessionId);
      const memoryItems = deps.agent.getMemoryStore().listEntries({
        workspaceDir: resolved.workspaceDir,
        includeUser: false,
        includeExpired: true,
        includeSuperseded: true,
      });
      const skillItems = listWorkspaceSkills(deps, resolved.workspaceDir);
      const auditItems = deps.agent.listGovernanceAudit({
        sessionId: resolved.sessionId,
        workspaceDir: resolved.workspaceDir,
        limit: 40,
      });
      const latestSkillGovernanceReport =
        deps.governanceServices.getLatestWorkspaceSkillGovernanceReport(resolved.workspaceDir);
      res.json({
        workspaceDir: resolved.workspaceDir,
        memoryItems,
        skillItems,
        auditItems,
        latestSkillGovernanceReport,
      });
    } catch (error) {
      res.status(500).json({ error: error instanceof Error ? error.message : String(error) });
    }
  });

  deps.app.post('/api/governance/skills/run', async (req: Request, res: Response) => {
    let resolved: ReturnType<typeof resolveGovernanceRouteContext>;
    try {
      resolved = resolveGovernanceRouteContext(deps, (req.body as { sessionId?: string }).sessionId ?? req.query.sessionId);
      if (resolved.context && rejectObserveOnlyIfNeeded(deps, resolved.context, res)) {
        return;
      }
      const report = await deps.governanceServices.runWorkspaceSkillGovernance({
        workspaceDir: resolved.workspaceDir,
      });
      appendSkillGovernanceAudit(deps, {
        sessionId: resolved.sessionId,
        workspaceDir: resolved.workspaceDir,
        report,
      });
      res.json({ success: true, report });
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      if (message.includes('already running')) {
        res.status(409).json({ error: message });
        return;
      }
      res.status(500).json({ error: message });
    }
  });

  deps.app.patch('/api/memory/:id', (req: Request, res: Response) => {
    try {
      const body = (req.body ?? {}) as { sessionId?: string; title?: string; content?: string };
      const resolved = resolveGovernanceRouteContext(deps, body.sessionId ?? req.query.sessionId);
      if (resolved.context && rejectObserveOnlyIfNeeded(deps, resolved.context, res)) {
        return;
      }
      const content = String(body.content ?? '');
      if (!content.trim()) {
        res.status(400).json({ error: 'content is required' });
        return;
      }
      const entry = deps.agent.updateMemoryEntry({
        id: req.params.id,
        title: body.title,
        content,
        workspaceDir: resolved.workspaceDir,
        sessionId: resolved.sessionId,
      });
      if (!entry) {
        res.status(404).json({ error: 'Memory entry not found' });
        return;
      }
      res.json({ success: true, entry });
    } catch (error) {
      res.status(400).json({ error: error instanceof Error ? error.message : String(error) });
    }
  });

  deps.app.patch('/api/skills/workspace/:skillName', (req: Request, res: Response) => {
    try {
      const body = (req.body ?? {}) as { sessionId?: string; content?: string };
      const resolved = resolveGovernanceRouteContext(deps, body.sessionId ?? req.query.sessionId);
      if (resolved.context && rejectObserveOnlyIfNeeded(deps, resolved.context, res)) {
        return;
      }
      const content = String(body.content ?? '');
      if (!content.trim()) {
        res.status(400).json({ error: 'content is required' });
        return;
      }
      const result = deps.agent.updateWorkspaceSkillContent({
        name: req.params.skillName,
        workspaceDir: resolved.workspaceDir,
        content,
        sessionId: resolved.sessionId,
      });
      if (!result) {
        res.status(404).json({ error: 'Workspace skill not found' });
        return;
      }
      res.json({ success: true, result });
    } catch (error) {
      res.status(400).json({ error: error instanceof Error ? error.message : String(error) });
    }
  });
}
